[project]
name = "hydroatlas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Czepielik", email = "adam.czepielik@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "click>=8.5.0",
    "httpx>=0.28.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyyaml>=6.0.3",
]

[project.scripts]
hydroatlas = "hydroatlas:main"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
